from django.urls import path
from .views import (
    generate_ai_meal_plan, 
    track_meal_item, 
    daily_nutrition, 
    get_meal_plan, 
    check_active_plan, 
    generate_meal_image_endpoint,
    recalculate_meal_plan,
    generate_ai_workout_plan,
    generate_ai_marathon_plan,
    get_user_workout_plans,
    get_user_marathon_plans,
    regenerate_workout_plan,
    delete_current_meal_plan,
    get_active_workout_plan,
    track_workout_exercise,
    complete_workout_plan,
    get_active_marathon_plan,
    track_marathon_day,
    complete_marathon_week,
    log_workout_calories,
    log_marathon_calories,
    get_daily_workout_summary,
    # New daily workout system
    generate_daily_workout,
    complete_daily_workout,
    get_todays_workout,
    check_active_workout_plan,
    check_active_marathon_plan
)

urlpatterns = [
    path("generate-ai-meal-plan/", generate_ai_meal_plan),
    path("meal-plan/", get_meal_plan),
    path("track-meal-item/", track_meal_item),
    path("daily_nutrition/", daily_nutrition),
    path("check-active-plan/", check_active_plan),
    path("generate-meal-image/", generate_meal_image_endpoint),
    path("recalculate-meal-plan/", recalculate_meal_plan),
    path("delete-meal-plan/", delete_current_meal_plan),
    path("workout-plan/", generate_ai_workout_plan),
    path("marathon-plan/", generate_ai_marathon_plan),
    path("workout-plans/", get_user_workout_plans),
    path("marathon-plans/", get_user_marathon_plans),
    path("regenerate-workout-plan/", regenerate_workout_plan),
    path("active-workout-plan/", get_active_workout_plan),
    path("track-workout-exercise/", track_workout_exercise),
    path("complete-workout-plan/", complete_workout_plan),
    path("active-marathon-plan/", get_active_marathon_plan),
    path("track-marathon-day/", track_marathon_day),
    path("complete-marathon-week/", complete_marathon_week),
    path("log-workout-calories/", log_workout_calories),
    path("log-marathon-calories/", log_marathon_calories),
    path("daily-workout-summary/", get_daily_workout_summary),
    # New daily workout system
    path("generate-daily-workout/", generate_daily_workout),
    path("complete-daily-workout/", complete_daily_workout),
    path("todays-workout/", get_todays_workout),
    path("check-active-workout-plan/", check_active_workout_plan),
    path("check-active-marathon-plan/", check_active_marathon_plan),
]
