# Generated by Django 5.2.7 on 2025-11-07 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('steps', models.IntegerField(default=0)),
                ('calories_burned', models.FloatField(default=0.0)),
                ('distance', models.FloatField(default=0.0, help_text='Distance in km')),
                ('active_minutes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_data',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='health_data_user_id_6a99ee_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HeartRateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('heart_rate', models.IntegerField(help_text='BPM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_rate_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'heart_rate_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='heart_rate__user_id_00ca6a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SleepData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sleep_duration', models.FloatField(help_text='Hours of sleep')),
                ('sleep_quality', models.CharField(choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sleep_data',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(choices=[('running', 'Running'), ('cycling', 'Cycling'), ('walking', 'Walking'), ('gym', 'Gym'), ('yoga', 'Yoga'), ('swimming', 'Swimming'), ('other', 'Other')], max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('calories_burned', models.FloatField(default=0.0)),
                ('distance', models.FloatField(blank=True, help_text='Distance in km', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workout_sessions',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['user', 'start_time'], name='workout_ses_user_id_1b7cf4_idx')],
            },
        ),
    ]
