# Generated by Django 5.2.8 on 2026-02-01 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='age',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='height',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='weight',
        ),
        migrations.CreateModel(
            name='WaterIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField(help_text='Water intake in liters')),
                ('goal', models.FloatField(default=3.0, help_text='Daily water goal in liters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_intake', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'water_intake',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='water_intak_user_id_3475ab_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
