# Generated by Django 5.2.8 on 2026-02-01 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0002_remove_diet_activity_remove_diet_age_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_calories', models.FloatField(default=0)),
                ('total_protein', models.FloatField(default=0)),
                ('total_carbs', models.FloatField(default=0)),
                ('total_fat', models.FloatField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_nutrition_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_nutrition_log',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='daily_nutri_user_id_5b757e_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
