# Generated by Django 5.2.8 on 2026-02-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0003_dailynutritionlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutSession',
        ),
    ]
