# Generated by Django 5.2.8 on 2026-02-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0004_remove_workoutsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='feedback_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='is_daily_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='plan_day_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='user_feedback',
            field=models.CharField(blank=True, choices=[('easy', 'Too Easy'), ('just_right', 'Just Right'), ('difficult', 'Too Difficult')], max_length=20, null=True),
        ),
    ]
