# Generated by Django 5.2.8 on 2026-02-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0002_remove_userbodyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
