# Generated by Django 5.2.8 on 2026-02-05 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0003_dailynutritionlog'),
        ('ml_models', '0003_mealitem_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarathonDayTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('just_right', 'Just Right'), ('difficult', 'Difficult')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_tracking', to='health_data.marathon')),
            ],
            options={
                'db_table': 'marathon_day_tracking',
                'ordering': ['day_index'],
                'unique_together': {('marathon', 'day_index')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutExerciseTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_index', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('just_right', 'Just Right'), ('difficult', 'Difficult')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_tracking', to='health_data.workout')),
            ],
            options={
                'db_table': 'workout_exercise_tracking',
                'ordering': ['exercise_index'],
                'unique_together': {('workout', 'exercise_index')},
            },
        ),
    ]
